### ISSUE TITLE
Compilation error: module `MatlabParser` is missing

### ISSUE THREAD

**Issue by japdlsd** [MrRedstoner/Matlab2Python#1]
Compilation error:
```
~/tmp/Matlab2Python/matlab2python/src/main/java/sk/uniba/grman19/util/PureConstantExtractorVisitor.java:13:37
java: package sk.uniba.grman19.MatlabParser does not exist
```

**Comment by japdlsd** [comment]
It may be a good idea to add specific instructions on how to generate the ANTLR4 parsers and then add them to the expected directory

**Comment by MrRedstoner** [comment]
How exactly are you building the project? Running 'mvn clean package' should generate and place the classes in the expected location, when running the antlr4-maven-plugin step. build-helper-maven-plugin should then pick them up.

An IDE might require you to explicitly add the path to the generated classes as a path with files to compile. Files are generated under target/generated-sources/antlr4/

**Comment by japdlsd** [comment]
I tried the latter option (IDE default build), which led to the aforementioned problem. I then ran the ANTLR4 and moved the generated files manually. After that, everything went smoothly. 

All in all, these two solutions could be specified explicitly in the documentation of this repository.

So, maybe this issue should really be named "Build instructions missing"

**Comment by MrRedstoner** [comment]
Fair enough, but there should be no need to manually move the files, it should be sufficient to inform the IDE of their existence where they are generated.
